# jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    jest:
      uris: http://192.168.188.100:9200
# mybatis配置
mybatis:
  type-aliases-package: com.bai.gmall.entity
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# 服务端口号
server:
  port: 8074
logging:
  level:
    root: info
    #com.bai.gmall.manage.dao: debug
    #com.bai.gmall.service: debug
    #com.bai.gmall.user.controller: debug
mapper:
  identity: MYSQL